#!/usr/bin/env bash

gensecp () {
  openssl ecparam -name secp384r1 -genkey -noout -out secp384r1.pem
  openssl ec -in secp384r1.pem -pubout -out secp384r1.pub
}

derive () {
  openssl pkeyutl -derive -inkey secp384r1.pem -peerkey peerpub.pem -out secret.bin
}


mkdir /var/heaven-pki 2>/dev/null
cd /var/heaven-pki

export val=$(echo "$@" | awk '{print $7}' | cut -d'/' -f6 | base64 -d)
echo "$@" | awk '{print $7}' | cut -d'/' -f7 | base64 -d > peerpub.pem
gensecp
derive
mv secp384r1.pem "$val".lastkey.pem
cp peerpub.pem "$val".peerpub.pem
export GPXENV=$(cat secret.bin | base64 | sed 's/\//3/g' | sed 's/=/t/g' | tr -d '\n')
cp input.list input.list.holding
echo $val > input.list
./identity-build
mv input.list.holding input.list
